name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew build -Paxolotlclient.modules.all=false -Paxolotlclient.modules.1.21=true

      - uses: actions/upload-artifact@v4
        with:
          name: axolotlclient-1.21
          path: versions/1.21/build/libs/*.jar
